In [2]:
using Pkg
Pkg.add("CSV")
Pkg.add("DataFrames")
using CSV
using DataFrames
using Random



df = CSV.read("../dataset/Iris.csv", DataFrame)


    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...


  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


150×6 DataFrame
 Row │ Id     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Specie ⋯
     │ Int64  Float64        Float64       Float64        Float64       String ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │     1            5.1           3.5            1.4           0.2  Iris-s ⋯
   2 │     2            4.9           3.0            1.4           0.2  Iris-s
   3 │     3            4.7           3.2            1.3           0.2  Iris-s
   4 │     4            4.6           3.1            1.5           0.2  Iris-s
   5 │     5            5.0           3.6            1.4           0.2  Iris-s ⋯
   6 │     6            5.4           3.9            1.7           0.4  Iris-s
   7 │     7            4.6           3.4            1.4           0.3  Iris-s
   8 │     8            5.0           3.4            1.5           0.2  Iris-s
  ⋮  │   ⋮          ⋮             ⋮              ⋮             ⋮               ⋱
 144 │   144            6.8           3.2            5.9           2.3  Iris-v ⋯
 145 │   145            6.7           3.3            5.7           2.5  Iris-v
 146 │   146            6.7           3.0            5.2           2.3  Iris-v
 147 │   147            6.3           2.5            5.0           1.9  Iris-v
 148 │   148            6.5           3.0            5.2           2.0  Iris-v ⋯
 149 │   149            6.2           3.4            5.4           2.3  Iris-v
 150 │   150            5.9           3.0            5.1           1.8  Iris-v
                                                   1 column and 135 rows omitted

In [12]:
C = cat([10 15; 20 25], [30 35; 40 45],
        [50 55; 60 65], [70 75; 80 85], dims=3);
        


4


In [16]:
X = [1 2 3; 4 5 6;7 8 9]
θ = [1,1,1]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [ ]:
map((θ,idx) -> 

In [3]:
X = hcat(ones(150),Matrix(df[:,2:4]))


y = df[:,5]

150-element Vector{Float64}:
 0.2
 0.2
 0.2
 0.2
 0.2
 0.4
 0.3
 0.2
 0.2
 0.1
 ⋮
 2.3
 1.9
 2.3
 2.5
 2.3
 1.9
 2.0
 2.3
 1.8

In [37]:
#Hypo function
h(x,θ) = θ'x


h (generic function with 1 method)

In [3]:
size(df)[2]




6

In [2]:
test = 1
test += 1
test

2

In [5]:
θ = Vector{Int}(undef,30)
rand!(θ,1:100)
θ

30-element Vector{Int64}:
 35
 75
 58
  5
 29
  4
 38
 12
 35
 42
  ⋮
 32
 53
 40
 40
 61
 21
  5
  7
 82

In [135]:
#Declaring global varib
X = hcat(ones(150),Matrix(df[:,2:4])) #design matrix
θ = Vector{Float64}(undef,size(X)[2])
rand!(θ,1:100)
y = df[:,5]

#hypothesis function
h(x) = θ'x

#cost function J
#J(θ::Vector) = (X*θ-y)'(X*θ-y)

J(θ::Vector) = 0.5*sum((X*θ-y).*(X*θ-y))

"""
function LMSUpdateRule(xi,yi,α,θj,idxθj)
    θj .+= α*(yi - h(xi))*xi[idxθj]
    return θj
    end;
"""

function BatchGradientDescent(X,y,epochs,α)
    for epoch in 1:epochs
        println(epoch)
        for (idxθj,θj) in enumerate(θ)
            batchsum = 0
            for (row_index, x) in enumerate(eachrow(X))
                batchsum += (y[row_index] - h(x))*x[idxθj]
            end;
            println("batchsum: " ,batchsum)
            θj += α*batchsum
            θ[idxθj] = θj
        end;
        println("Cost Func:", J(θ))
    end;
    return θ
    end;




BatchGradientDescent(X,y,0.1)
#h(X[1,:])

#println(J(θ))
J(BatchGradientDescent(X,y,5,0.000001))

1
batchsum: -2.1788312619747297e13
batchsum: -1.346686147019553e14
batchsum: -6.430375366092666e13
batchsum: -9.93309610103612e13
Cost Func:1.900102086323842e24
2
batchsum: -2.158154698669836e13
batchsum: -1.3342836189225698e14
batchsum: -6.367944690759838e13
batchsum: -9.849073002898417e13
Cost Func:1.8681396563955452e24
3
batchsum: -2.1376659167233086e13
batchsum: -1.3219936264702131e14
batchsum: -6.306081403377864e13
batchsum: -9.765810255635867e13
Cost Func:1.836753088741786e24
4
batchsum: -2.117363212986774e13
batchsum: -1.3098151490099595e14
batchsum: -6.244780357711266e13
batchsum: -9.68330096374812e13
Cost Func:1.8059319855650693e24
5
batchsum: -2.097244899758523e13
batchsum: -1.2977471751460614e14
batchsum: -6.184036454198275e13
batchsum: -9.6015382942732e13
Cost Func:1.7756661368206593e24


1.7756661368206593e24

In [120]:
sum((X*θ-y).*(X*θ-y))

NaN

In [10]:
J(θ) = (0.5)(X*θ-y)'(X*θ-y)

J (generic function with 1 method)